spring:
  application:
    name: NutriAI
  profiles:
    active: dev # dev, prod

  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""

      resource server:
        jwt:
          issuer-uri: ""

  data:
    mongodb:
      uri: mongodb+srv://hieudoanw11:pDeujv3Wpc5K54xj@cluster0.tuyao3c.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: nutri_meal
      auto-index-creation: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 30m

logging:
  config: classpath:logback-${spring.profiles.active}.xml
