spring:
  application:
    name: NutriAI

  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""

      resource server:
        jwt:
          issuer-uri: ""

  data:
    mongodb:
      uri: mongodb://localhost:27017/nutriai

server:
  port: 8080
