spring:
  application:
    name: NutriAI
  profiles:
    active: dev # dev, prod

  main:
    banner-mode: off
    lazy-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri:
              - https://www.getpostman.com/oauth2/callback
              - http://localhost:8000/login/oauth2/code/google
            client-authentication-method:
              - client_secret_basic
            authorization-grant-type:
              - authorization_code
              - refresh_token
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

      resource server:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
      auto-index-creation: true
      uuid-representation: standard

  jpa:
    show-sql: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 30m

logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    "[org.springframework.data.mongodb.core.MongoTemplate]": DEBUG
    "[org.springframework.web]": DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-docs
    url: /openapi.yaml
  writer-with-order-by-keys: true
