spring:
  application:
    name: NutriAI
  profiles:
    active: dev # dev, prod

  main:
    banner-mode: off
    lazy-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""

      resource server:
        jwt:
          issuer-uri: ""

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: nutri_meal
      auto-index-creation: true
      uuid-representation: standard

  jpa:
    show-sql: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 30m

logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    "[org.springframework.data.mongodb.core.MongoTemplate]": DEBUG
    "[org.springframework.web]": DEBUG
